name: ecommerseapp
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.0.dev

dependencies:
  flutter:
    sdk: flutter

# utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
 
 #icons 
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

#state managamet
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets: 
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/images/emailverfication/

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800


        
          
          
        

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
